language: php

php:
  - hhvm
  - 5.3
  - 5.4
  - 5.5
  - 5.6

install:
    # Install deps
    - composer install --no-dev

script:
    - mkdir -p build/logs
    - phpunit

after_script:

    # Upload coverage to scrutinizer
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml

    # Upload coverage to coveralls.io
    - php bin/coveralls -p
